---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=1.9.3
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.8.4
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - echo -e 'localhost  ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg
script:
  - ansible-playbook --syntax-check tests/test.yml
  - ansible-playbook --sudo -v --diff tests/test.yml
  - >
    ansible-playbook --sudo tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
